//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý học sinh.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại trang chủ.
        /// </summary>
        public static string BackToHomepage {
            get {
                return ResourceManager.GetString("BackToHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn giới tính.
        /// </summary>
        public static string ChooseGender {
            get {
                return ResourceManager.GetString("ChooseGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp.
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp học.
        /// </summary>
        public static string ClassLong {
            get {
                return ResourceManager.GetString("ClassLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn hủy, các thay đổi sẽ không được lưu?.
        /// </summary>
        public static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm lớp học.
        /// </summary>
        public static string CreateClass {
            get {
                return ResourceManager.GetString("CreateClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo báo cáo tổng kết học kỳ.
        /// </summary>
        public static string CreateSemesterReport {
            get {
                return ResourceManager.GetString("CreateSemesterReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm học sinh.
        /// </summary>
        public static string CreateStudent {
            get {
                return ResourceManager.GetString("CreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm môn học.
        /// </summary>
        public static string CreateSubject {
            get {
                return ResourceManager.GetString("CreateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo báo cáo tổng kết môn học.
        /// </summary>
        public static string CreateSubjectReport {
            get {
                return ResourceManager.GetString("CreateSubjectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo bảng điểm.
        /// </summary>
        public static string CreateTranscript {
            get {
                return ResourceManager.GetString("CreateTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị này phải là một ngày.
        /// </summary>
        public static string DateOnlyError {
            get {
                return ResourceManager.GetString("DateOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa {0} có {1} .
        /// </summary>
        public static string DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phát triển bởi helloVanDuc.
        /// </summary>
        public static string DevelopeByHelloVanDuc {
            get {
                return ResourceManager.GetString("DevelopeByHelloVanDuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xong.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin lớp học.
        /// </summary>
        public static string EditClass {
            get {
                return ResourceManager.GetString("EditClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin học sinh.
        /// </summary>
        public static string EditStudent {
            get {
                return ResourceManager.GetString("EditStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin môn học.
        /// </summary>
        public static string EditSubject {
            get {
                return ResourceManager.GetString("EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải là một địa chỉ email.
        /// </summary>
        public static string EmailAddressError {
            get {
                return ResourceManager.GetString("EmailAddressError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm 15 phút.
        /// </summary>
        public static string FifteenMinutesTestScore {
            get {
                return ResourceManager.GetString("FifteenMinutesTestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm cuối kỳ.
        /// </summary>
        public static string FinalTestScore {
            get {
                return ResourceManager.GetString("FinalTestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBHK1.
        /// </summary>
        public static string FirstSemesterAverageScore {
            get {
                return ResourceManager.GetString("FirstSemesterAverageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm 1 tiết.
        /// </summary>
        public static string FortyFiveMinutesTestScore {
            get {
                return ResourceManager.GetString("FortyFiveMinutesTestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khối.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách lớp học.
        /// </summary>
        public static string ListClasses {
            get {
                return ResourceManager.GetString("ListClasses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách quy định.
        /// </summary>
        public static string ListRules {
            get {
                return ResourceManager.GetString("ListRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bảng điểm.
        /// </summary>
        public static string ListScripts {
            get {
                return ResourceManager.GetString("ListScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách học sinh.
        /// </summary>
        public static string ListStudents {
            get {
                return ResourceManager.GetString("ListStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách môn học.
        /// </summary>
        public static string ListSubjects {
            get {
                return ResourceManager.GetString("ListSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mục lục.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sĩ số.
        /// </summary>
        public static string NumberOfStudentsInClass {
            get {
                return ResourceManager.GetString("NumberOfStudentsInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng đạt.
        /// </summary>
        public static string NumberOfStudentsPass {
            get {
                return ResourceManager.GetString("NumberOfStudentsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị này phải là một số.
        /// </summary>
        public static string NumberOnlyError {
            get {
                return ResourceManager.GetString("NumberOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có {1}: {2} đã tồn tại, vui lòng chọn {1} khác.
        /// </summary>
        public static string ObjectAlreadyExists {
            get {
                return ResourceManager.GetString("ObjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} với {1}: {2} không tồn tại.
        /// </summary>
        public static string ObjectDoesNotExists {
            get {
                return ResourceManager.GetString("ObjectDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} có {1}: {2} đã bị thay đổi sau khi bạn tải chúng.
        /// </summary>
        public static string ObjectHasBeenUpdated {
            get {
                return ResourceManager.GetString("ObjectHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sĩ số của một lớp không được vượt quá {0} học sinh.
        /// </summary>
        public static string OutOfMaximumNumberOfStudentsInClass {
            get {
                return ResourceManager.GetString("OutOfMaximumNumberOfStudentsInClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} phải thuộc khoảng từ {1} đến {2}.
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo học kì.
        /// </summary>
        public static string ReportSemester {
            get {
                return ResourceManager.GetString("ReportSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo môn học.
        /// </summary>
        public static string ReportSubject {
            get {
                return ResourceManager.GetString("ReportSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị này không được bỏ trống.
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một (một số) trường giá trị bắt buộc bị thiếu.
        /// </summary>
        public static string RequiredFieldMissing {
            get {
                return ResourceManager.GetString("RequiredFieldMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy định.
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên quy định.
        /// </summary>
        public static string RuleName {
            get {
                return ResourceManager.GetString("RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng điểm.
        /// </summary>
        public static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra cứu.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tra cứu điểm.
        /// </summary>
        public static string SearchTranscript {
            get {
                return ResourceManager.GetString("SearchTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBHK2.
        /// </summary>
        public static string SecondSemesterAverageScore {
            get {
                return ResourceManager.GetString("SecondSemesterAverageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học kỳ.
        /// </summary>
        public static string Semester {
            get {
                return ResourceManager.GetString("Semester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo tổng kết học kỳ.
        /// </summary>
        public static string SemesterReport {
            get {
                return ResourceManager.GetString("SemesterReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được vượt quá {1} kí tự.
        /// </summary>
        public static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học sinh.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ tuổi của học sinh phải từ {0} tới {1}.
        /// </summary>
        public static string StudentAgeInvalid {
            get {
                return ResourceManager.GetString("StudentAgeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học sinh với mã số {0} đã có lớp học, bạn không thể thêm học sinh này vào lớp khác.
        /// </summary>
        public static string StudentAlreadyHaveClass {
            get {
                return ResourceManager.GetString("StudentAlreadyHaveClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số học sinh.
        /// </summary>
        public static string StudentId {
            get {
                return ResourceManager.GetString("StudentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số học sinh đã tồn tại, vui lòng chọn mã số khác.
        /// </summary>
        public static string StudentIdAlreadyExist {
            get {
                return ResourceManager.GetString("StudentIdAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn học.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo tổng kết môn học.
        /// </summary>
        public static string SubjectReport {
            get {
                return ResourceManager.GetString("SubjectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng điểm.
        /// </summary>
        public static string Transcript {
            get {
                return ResourceManager.GetString("Transcript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết bảng điểm.
        /// </summary>
        public static string TranscriptDetail {
            get {
                return ResourceManager.GetString("TranscriptDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn học/Lớp/Học kỳ.
        /// </summary>
        public static string TranscriptOfClass {
            get {
                return ResourceManager.GetString("TranscriptOfClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu dữ liệu.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị không hợp lệ, không thể chuyển về kiểu dữ liệu phù hợp của quy định.
        /// </summary>
        public static string UnableToCast {
            get {
                return ResourceManager.GetString("UnableToCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật quy định.
        /// </summary>
        public static string UpdateRule {
            get {
                return ResourceManager.GetString("UpdateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bảng điểm.
        /// </summary>
        public static string UpdateTranscript {
            get {
                return ResourceManager.GetString("UpdateTranscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
